#! /bin/sh
#
#
set -ex

alias staging_gcloud='/google/data/ro/teams/cloud-sdk/gcloud'

instance1=$1

staging_gcloud compute scp ./tools/net/ynl/ \
  $instance1:~/ --recurse
staging_gcloud compute scp ./Documentation/netlink/specs/netdev.yaml \
  $instance1:~/ynl/ --recurse
gcloud compute scp ./Documentation/netlink $instance1:~/ --recurse

staging_gcloud compute ssh $instance1 -- \
  "sudo mount -o remount,exec /home && \
   sudo iptables -I INPUT -p tcp -m tcp -j ACCEPT && \
   sudo ethtool -K eth1 ntuple on || true"
