#! /bin/sh
#
#
set -ex

alias staging_gcloud='/google/data/ro/teams/cloud-sdk/gcloud'

instance1=$1
instance2=$2

random_port=$((RANDOM%100+5201))
echo $random_port


sudo make headers_install
make -C tools/net/ynl/lib
make -C tools/net/ynl/generated/
pushd ./tools/testing/selftests/net
CFLAGS="-static" make ncdevmem
popd

set +e
staging_gcloud compute scp ./tools/testing/selftests/net/ncdevmem $instance1:~/
staging_gcloud compute scp ./tools/testing/selftests/net/ncdevmem $instance2:~/
set -e

CLIENT=$(staging_gcloud compute ssh $instance2 -- "ifconfig | grep -i 'inet 192.168.1.'" | awk '{print $2}')
SERVER=$(staging_gcloud compute ssh $instance1 -- "ifconfig | grep -i 'inet 192.168.1.'" | awk '{print $2}')

sed -i "s/SERVER/$SERVER/g" scripts/server
sed -i "s/CLIENT/$CLIENT/g" scripts/server
sed -i "s/SERVER/$SERVER/g" scripts/client
sed -i "s/CLIENT/$CLIENT/g" scripts/client
sed -i "s/SERVER/$SERVER/g" scripts/queue-api-client
sed -i "s/CLIENT/$CLIENT/g" scripts/queue-api-client
sed -i "s/SERVER/$SERVER/g" scripts/queue-api-server
sed -i "s/CLIENT/$CLIENT/g" scripts/queue-api-server

staging_gcloud compute scp scripts/server $instance1:~/
staging_gcloud compute scp scripts/client $instance2:~/
staging_gcloud compute scp scripts/tx-server $instance1:~/
staging_gcloud compute scp scripts/tx-client $instance2:~/
staging_gcloud compute scp scripts/queue-api-server $instance1:~/
staging_gcloud compute scp scripts/queue-api-client $instance2:~/

staging_gcloud compute scp ./lib/bench_page_pool_simple.ko $instance1:~/
staging_gcloud compute scp ./lib/bench_page_pool_simple.ko $instance2:~/

staging_gcloud compute scp ~/neper/tcp_stream $instance1:~/
staging_gcloud compute scp ~/neper/tcp_stream $instance2:~/

sed -i "s/$SERVER/SERVER/g" scripts/server
sed -i "s/$CLIENT/CLIENT/g" scripts/server
sed -i "s/$SERVER/SERVER/g" scripts/client
sed -i "s/$CLIENT/CLIENT/g" scripts/client
sed -i "s/$SERVER/SERVER/g" scripts/queue-api-client
sed -i "s/$CLIENT/CLIENT/g" scripts/queue-api-client
sed -i "s/$SERVER/SERVER/g" scripts/queue-api-server
sed -i "s/$CLIENT/CLIENT/g" scripts/queue-api-server

staging_gcloud compute ssh $instance1 -- \
  "sudo mount -o remount,exec /home && \
   sudo iptables -I INPUT -p tcp -m tcp -j ACCEPT && \
   sudo /home/almasrymina_google_com/ethtool -K eth1 ntuple on || true && \
   sudo /home/almasrymina_google_com/ethtool -G eth1 tcp-data-split on"

staging_gcloud compute ssh $instance2 -- \
  "sudo mount -o remount,exec /home && \
   sudo iptables -I INPUT -p tcp -m tcp -j ACCEPT && \
   sudo /home/almasrymina_google_com/ethtool -K eth1 ntuple on || true && \
   sudo /home/almasrymina_google_com/ethtool -G eth1 tcp-data-split on"
