#!/bin/sh

alias staging_gcloud='/google/data/ro/teams/cloud-sdk/gcloud'

instance1=$1
instance2=$2

echo $instance1
CLIENT=$(staging_gcloud compute ssh $instance2 -- "ifconfig | grep -i 'inet 192.168.0.'" | awk '{print $2}')
SERVER=$(staging_gcloud compute ssh $instance1 -- "ifconfig | grep -i 'inet 192.168.0.'" | awk '{print $2}')
USER=mina

echo
echo
echo "docker-credential-gcr configure-docker"
echo "export CLIENT=$CLIENT SERVER=$SERVER USER=$USER IS_SERVER=yes && ./start_tcpdirectd_cos"
echo "export CLIENT=$CLIENT SERVER=$SERVER USER=$USER && ./start_tcpdirectd_cos"
echo
echo
echo perf test
echo ./run_benchmark --gpus 0,1,2,3,4,5,6,7 --ifnames eth1,eth1,eth2,eth2,eth3,eth3,eth4,eth4 --use_dmabuf --port 5201 --num_gpus=8 --message_size 819200 --server_address=$SERVER --socket_per_thread 1 --threads_per_gpu 16 --skip_rx_copy --server
echo ./run_benchmark --gpus 0,1,2,3,4,5,6,7 --ifnames eth1,eth1,eth2,eth2,eth3,eth3,eth4,eth4 --use_dmabuf --port 5201 --num_gpus=8 --message_size 819200 --server_address=$SERVER --socket_per_thread 1 --threads_per_gpu 16 --skip_rx_copy

echo
echo
echo validation test
echo ./run_benchmark --gpus 0,1,2,3,4,5,6,7 --ifnames eth1,eth1,eth2,eth2,eth3,eth3,eth4,eth4 --use_dmabuf --port 5201 --num_gpus=1 --message_size 819200 --server_address=$SERVER --socket_per_thread 1 --threads_per_gpu 2 --sliding_window=1 --do_validation --server
echo ./run_benchmark --gpus 0,1,2,3,4,5,6,7 --ifnames eth1,eth1,eth2,eth2,eth3,eth3,eth4,eth4 --use_dmabuf --port 5201 --num_gpus=1 --message_size 819200 --server_address=$SERVER --socket_per_thread 1 --threads_per_gpu 2 --sliding_window=1 --do_validation

echo
echo
echo rx-only perf
echo ./run_benchmark --gpus 0,1,2,3,4,5,6,7 --ifnames eth1,eth1,eth2,eth2,eth3,eth3,eth4,eth4 --use_dmabuf --port 5201 --num_gpus=1 --message_size 819200 --server_address=$SERVER --socket_per_thread 1 --threads_per_gpu 16 --skip_rx_copy --notcpdirect_tx --server
echo ./run_benchmark --gpus 0,1,2,3,4,5,6,7 --ifnames eth1,eth1,eth2,eth2,eth3,eth3,eth4,eth4 --use_dmabuf --port 5201 --num_gpus=1 --message_size 819200 --server_address=$SERVER --socket_per_thread 1 --threads_per_gpu 16 --skip_rx_copy --notcpdirect_tx
